Fix responsive lateral menu
BrightCoders-Institute/BCDIC22-RoR-proyecto-final-team4 pull request #108
Opened 2023-04-04 22:48 UTC by DiegoCoronaBarragan

# Description

I use styles to adjust the lateral menu in mobile view.

## Screenshots

![image](https://user-images.githubusercontent.com/116856441/229938933-885e86f8-b11d-4c31-91be-d9ed630ede00.png)

2023-04-05 18:13 UTC, claunicole approved these changes

2023-04-05 20:20 UTC, YilKanda requested changes
I have a question, why does the menu icon appear as vertical lines, instead of horizontal lines? Try to use standard icons that most users understand what they mean.

2023-04-05 20:20 UTC, YilKanda commented on app/assets/stylesheets/pages/_main.scss
> +
Remove unnecessary spaces

2023-04-05 20:20 UTC, YilKanda commented on app/javascript/navbarService.js
> +    // document.getElementById("mainService").style.background = "none";
Code that you do not use delete it.

2023-04-05 20:20 UTC, YilKanda commented on app/javascript/navbarService.js
> +    // document.getElementById("mainService").style.background = "none";
Code that you do not use delete it.

2023-04-10 02:31 UTC, YilKanda approved these changes

2023-04-10 21:17 UTC, oscaregr approved these changes

2023-04-10 21:17 UTC, merged