edit and delete user counts
BrightCoders-Institute/BCDIC22-RoR-proyecto-final-team4 pull request #121
Opened 2023-04-12 22:29 UTC by EverardoAlcarazBaltazar

# Description

I implement a modal with a form to update or delete accounts because it is necessary to allow users to update or delete their accounts.

## Screenshots

![Screenshot from 2023-04-12 16-28-16](https://user-images.githubusercontent.com/72171554/231599959-912a4a86-14d0-4ca7-9a2c-cfff1c46322e.png)

2023-04-13 00:45 UTC, oscaregr requested changes
do a git rebase before to merge

2023-04-13 20:50 UTC, AangelF approved these changes

2023-04-13 21:42 UTC, oscaregr approved these changes

2023-04-13 22:51 UTC, DiegoMoralesBravo approved these changes

2023-04-13 23:45 UTC, YilKanda commented on app/assets/stylesheets/pages/_edit.scss
> +}
Add a blank line.

2023-04-13 23:45 UTC, YilKanda commented on app/assets/stylesheets/utilities/_variables.scss
> +$cancel-hover: #B71C1C;
Add a blank line

2023-04-13 23:45 UTC, YilKanda commented on app/assets/stylesheets/utilities/_variables.scss
> +$cancel-hover: #B71C1C;
Sort the variables

2023-04-13 23:45 UTC, YilKanda commented on app/views/devise/registrations/_edit.html.erb
> +    <%= javascript_include_tag 'modalAlert' %>
Add a blank line

2023-04-14 00:10 UTC, YilKanda approved these changes

2023-04-14 00:14 UTC, merged