Limit characters category
BrightCoders-Institute/BCDIC22-RoR-proyecto-final-team4 pull request #124
Opened 2023-04-12 23:18 UTC by DiegoCoronaBarragan

# Description

Limit the number of characters to 18 when creating a category.

## Screenshots

![image](https://user-images.githubusercontent.com/116856441/231606306-579d1b23-2132-462c-ab53-ea22b6e4ceb9.png)

2023-04-12 23:47 UTC, JuanequeX requested changes

2023-04-12 23:47 UTC, JuanequeX commented on app/assets/stylesheets/pages/_main.scss
> +            font-size: 25px;
Sort alphabetically this block

2023-04-12 23:47 UTC, JuanequeX commented on app/assets/stylesheets/pages/_main.scss
> +          background-color: none;
sort this block also

2023-04-13 00:38 UTC, JuanequeX approved these changes

2023-04-13 00:38 UTC, oscaregr approved these changes

2023-04-13 00:39 UTC, Ewar22 approved these changes
lgtm

2023-04-13 00:39 UTC, EverardoAlcarazBaltazar approved these changes

2023-04-13 00:39 UTC, merged