coupon/offer carousel added
BrightCoders-Institute/BCDIC22-RoR-proyecto-final-team4 pull request #46
Opened 2023-03-17 23:29 UTC by EverardoAlcarazBaltazar

# Description

I implement a coupon/offer carousel view because we want to show the coupons with the most likes in the carousel.

## Screenshots

![Screenshot from 2023-03-17 17-28-24](https://user-images.githubusercontent.com/72171554/226069302-9ac6a93c-e580-4bd4-913e-664a4570785f.png)

2023-03-18 00:23 UTC, oscaregr requested changes

2023-03-18 00:23 UTC, oscaregr commented on app/assets/stylesheets/pages/_main.scss
> +              background-color: $transparent-black;
sort this

2023-03-18 00:23 UTC, oscaregr commented on app/views/mainpages/_carousel.html.erb
> +    <%end%>
2 spaces for tab here

2023-03-22 01:06 UTC, oscaregr approved these changes

2023-03-22 01:35 UTC, claunicole approved these changes
LGTM!

2023-03-22 02:40 UTC, DiegoMoralesBravo approved these changes

2023-03-22 19:46 UTC, YilKanda approved these changes

2023-03-22 21:12 UTC, merged