finish the hidden menu left
BrightCoders-Institute/BCDIC22-RoR-proyecto-final-team4 pull request #58
Opened 2023-03-22 01:31 UTC by Ewar22

Finish hidden menu

# Description
Function to hide menu

## Screenshots

![image](https://user-images.githubusercontent.com/117693797/226778609-754717d4-6f62-4d9f-b303-9c1be3f89c7d.png)
![image](https://user-images.githubusercontent.com/117693797/226778585-ebfa04b2-e4be-45b8-955e-e4182236fd63.png)

2023-03-22 02:41 UTC, DiegoMoralesBravo approved these changes

2023-03-22 22:28 UTC, JorgeRodz requested changes

2023-03-22 22:28 UTC, JorgeRodz commented on app/javascript/navbarService.js
> +}
Add an empty line at the end.

2023-03-22 22:28 UTC, JorgeRodz commented on app/views/share/_menu.html.erb
> +</div>
Add an empty line at the end.

2023-03-22 22:40 UTC, claunicole approved these changes
LGTM!

2023-03-23 00:18 UTC, JorgeRodz approved these changes
Nice work! :+1:

2023-03-23 00:22 UTC, merged